inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 200

RSpec/StringAsInstanceDoubleConstant:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

