inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  CountAsOne: ['hash', 'heredoc', 'method_call']

RSpec/VerifiedDoubleReference:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

